// Auto-generated by Supreme SEO Engine — Do Not Edit

const postMetadata = {};

if (typeof module !== 'undefined' && module.exports) {
  module.exports.postMetadata = postMetadata;
} else if (typeof window !== 'undefined') {
  window.postMetadata = postMetadata;
}
