// Auto-generated by Supreme SEO Engine — Do Not Edit

const postMetadata = {
  "ats-friendly-resume-google-docs": {
    "title": "ats friendly resume google docs",
    "description": "Craft a resume that passes ATS filters and gets interviews using free Google Docs tools",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.111Z"
  },
  "best-free-resume-templates-docs": {
    "title": "Best Free Google Docs Resume Templates That Land Jobs",
    "description": "Discover top Google Docs resume templates that are free, modern, and easy to customize",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.122Z"
  },
  "budget-planner-google-docs-template": {
    "title": "budget planner google docs template",
    "description": "Get a clean, editable budget planner template in Google Docs with structured layout and aesthetic design for personal financial planning.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.126Z"
  },
  "business-letter-formal-template-docs": {
    "title": "Business Letter Template Google Docs: How to Write a Formal Letter Easily",
    "description": "Write polished formal business letters using free Google Docs templates built for professional communication",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.132Z"
  },
  "classroom-seating-chart-template-docs": {
    "title": "classroom seating chart template docs",
    "description": "Create and customize a classroom seating chart template using Google Docs or Slides. Learn methods, best practices, print and share your chart.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.138Z"
  },
  "cover-letter-template-matching-resume-docs": {
    "title": "cover letter template matching resume docs",
    "description": "Create your job-winning application fast using Google Docs cover letter and matching resume templates",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.146Z"
  },
  "create-professional-invoice-docs": {
    "title": "create professional invoice docs",
    "description": "Create clean, client-ready invoices in minutes with Google Docs",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.149Z"
  },
  "creative-resume-designers-docs": {
    "title": "creative resume designers docs",
    "description": "Download a stylish and professional creative resume template for graphic designers in Google Docs, free and easy to customize",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.151Z"
  },
  "daily-affirmation-journal-google-docs": {
    "title": "daily affirmation journal google docs",
    "description": "Free printable daily affirmation journal template in Google Docs to boost self-confidence, gratitude, and emotional resilience.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.153Z"
  },
  "daily-attendance-sheet-teachers-docs": {
    "title": "daily attendance sheet teachers docs",
    "description": "Teacher-friendly daily attendance sheet template in Google Docs with attendance status, notes, and summary features.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.157Z"
  },
  "daily-planner-google-docs-template": {
    "title": "daily planner google docs template",
    "description": "Download a clean, aesthetic daily planner template for Google Docs—editable, printable, and productivity-focused.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.160Z"
  },
  "delivery-note-template-docs": {
    "title": "delivery note template docs",
    "description": "Download a professional delivery note template in Google Docs to streamline your shipping process and improve customer communication.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.162Z"
  },
  "editable-class-schedule-template-docs": {
    "title": "editable class schedule template docs",
    "description": "Create and tailor a Google Docs class schedule template for students, teachers, or personal planning with step‑by‑step guidance and best practices.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.164Z"
  },
  "editable-report-card-template-docs": {
    "title": "editable report card template docs",
    "description": "Customizable, printable Google Docs report card template for teachers with sections for academics, behavior, attendance and comments.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.167Z"
  },
  "employee-timesheet-template-docs": {
    "title": "employee timesheet template docs",
    "description": "Track employee hours with a free Google Docs timesheet template that",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.168Z"
  },
  "fitness-tracker-template-google-docs": {
    "title": "fitness tracker template google docs",
    "description": "Free fitness tracker template in Google Docs to log workouts, track progress, and stay motivated. Easy to customize and download.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.173Z"
  },
  "free-lesson-plan-templates-teachers-docs": {
    "title": "free lesson plan templates teachers docs",
    "description": "Easily customizable free lesson plan templates in Google Docs to save time, stay organized, and streamline your teaching workflow",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.179Z"
  },
  "habit-tracker-google-docs-printable-template": {
    "title": "habit tracker google docs printable template",
    "description": "Download and customize a printable habit tracker using Google Docs or Sheets—clean, editable, and ready to print.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.180Z"
  },
  "homework-planner-template-docs": {
    "title": "homework planner template docs",
    "description": "Learn how to build or customize a student homework planner using Google Docs, with tips, templates, and best practices.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.182Z"
  },
  "how-to-format-a-manuscript-in-google-docs": {
    "title": "how to format a manuscript in google docs",
    "description": "Learn the correct manuscript formatting in Google Docs to prepare your writing for publishers, agents, or competitions with industry-standard settings.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.184Z"
  },
  "invoice-templates-freelancers-free-docs": {
    "title": "invoice templates freelancers free docs",
    "description": "Free Google Docs invoice templates built for freelancers—easy to edit, professional, and 100% free.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.185Z"
  },
  "make-letterhead-google-docs": {
    "title": "make letterhead google docs",
    "description": "Create professional letterheads in Google Docs with this step-by-step guide. Learn how to customize, save, and use your letterhead for business correspondence.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.186Z"
  },
  "meal-planner-template-google-docs": {
    "title": "meal planner template google docs",
    "description": "Discover an editable, aesthetic Google Docs meal planner template with weekly layout and grocery list to simplify healthy meal planning.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.187Z"
  },
  "meeting-minutes-template-free-docs": {
    "title": "meeting minutes template free docs",
    "description": "Download or copy a free Google Docs meeting minutes template to capture accurate, organized records for every kind of meeting",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.189Z"
  },
  "minimalist-calendar-template-google-docs": {
    "title": "minimalist calendar template google docs",
    "description": "Download or build a clean, printable minimalist calendar template in Google Docs. Includes yearly and monthly formats, customization tips, and FAQ.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.190Z"
  },
  "minimalist-resume-template-docs": {
    "title": "minimalist resume template docs",
    "description": "Discover the best minimalist resume template in Google Docs that blends simplicity, clarity, and professional appeal",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.191Z"
  },
  "modern-resume-templates-get-jobs": {
    "title": "Modern Resume Templates in Google Docs That Get Jobs",
    "description": "Sleek and modern Google Docs resume templates that recruiters love and job seekers trust",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.193Z"
  },
  "one-page-resume-template-free-docs": {
    "title": "one page resume template free docs",
    "description": "Download a free, modern one-page resume template in Google Docs to impress employers and pass ATS filters",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.195Z"
  },
  "parent-teacher-conference-form-template-docs": {
    "title": "parent teacher conference form template docs",
    "description": "Create and customize a Google Docs parent‑teacher conference form template for efficient meetings, documentation and communication.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.197Z"
  },
  "proposal-template-small-business-docs": {
    "title": "proposal template small business docs",
    "description": "Create clear, professional proposals with free Google Docs templates built for small business growth",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.200Z"
  },
  "purchase-order-template-small-stores": {
    "title": "purchase order template small stores",
    "description": "Download and customize a professional purchase order template in Google Docs. Perfect for small retail stores to track and manage supply purchases easily.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.202Z"
  },
  "reading-list-tracker-google-docs": {
    "title": "reading list tracker google docs",
    "description": "Organize your books with an editable, aesthetic reading list tracker template in Google Docs—designed for book lovers and goal planning.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.204Z"
  },
  "resume-career-changers-free-docs": {
    "title": "resume career changers free docs",
    "description": "Build your dream career with a free, customizable Google Docs resume designed for career changers",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.205Z"
  },
  "resume-remote-jobs-freezer-docs": {
    "title": "resume remote jobs freezer docs",
    "description": "Proven remote job resume template in Google Docs to boost your chances of landing interviews",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.207Z"
  },
  "resume-template-fresh-graduates-docs": {
    "title": "Google Docs Resume Template for Fresh Graduates",
    "description": "A professional guide to using Google Docs resume templates for first-time job seekers",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.209Z"
  },
  "sales-contract-template-docs": {
    "title": "sales contract template docs",
    "description": "Download an editable sales contract template in Google Docs to formalize transactions, protect both parties, and close deals confidently.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.215Z"
  },
  "student-planner-academic-docs": {
    "title": "student planner academic docs",
    "description": "Create and customize a Google Docs student planner template for the 2025 academic year. Free, printable, editable, and optimized for student life.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.217Z"
  },
  "student-progress-report-template-docs": {
    "title": "student progress report template docs",
    "description": "A clean, editable student progress report template in Google Docs with academic, attendance, and behavior sections.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.219Z"
  },
  "syllabus-template-college-professors-docs": {
    "title": "syllabus template college professors docs",
    "description": "A comprehensive guide to creating, customizing, and sharing an accessible Google Docs syllabus template tailored for college professors.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.220Z"
  },
  "weekly-planner-template-google-docs": {
    "title": "weekly planner template google docs",
    "description": "Beautiful and editable weekly planner template in Google Docs with clean aesthetic design, structured layout, and customizable features.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.222Z"
  },
  "yearly-goals-planner-google-docs-free-template": {
    "title": "yearly goals planner google docs free template",
    "description": "Plan your year with a clean, editable Google Docs yearly goals planner template. Break goals into action and track progress.",
    "image": "https://read.maxclickempire.com/assets/og-image.jpg",
    "published": "2025-07-28T14:06:43.223Z"
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports.postMetadata = postMetadata;
} else if (typeof window !== 'undefined') {
  window.postMetadata = postMetadata;
}
